### ISSUE TITLE
PyLaGriT math routine expects all string arguments and crashes when given a float

### ISSUE THREAD

**Issue by mhannonj** [lanl/LaGriT#180]
I'm attempting to run the arctic_w_ice_wedges example problem on PyLaGriT, and I get the following error message that pops up the first time the script attempts to run the math command.

Traceback (most recent call last):
  File "script.py", line 47, in <module>
    layer.math('sub',0.01*2,'zic')
  File "/home/mhannon/anaconda3/envs/py3_env/lib/python3.7/site-packages/pylagrit/pylagrit.py", line 3236, in math
    self.sendline('/'.join(cmd))
TypeError: sequence item 3: expected str instance, float found

**Comment by mhannonj** [comment]
A similar issue happens with the 'stack.stack_layers' command when I attempt running the artic_2d example problem.  It complains that the input stack_files is a list and not a string.  I attempted forcing everything to be a string with the str command, but that just caused other problems later on.

**Comment by daniellivingston** [comment]
@mhannonj it looks like this was resolved in fb8cb2bd15ac9703a64d4c0ee1b1802b11dd3348, can you verify?
